name: windows 

# ─────── Triggers ────────────────────────────────────────────────
#  • Manual run via “Run workflow” button
on:
  schedule:
    - cron: '30 13 * * *'  # Run daily at 10:30 AM UTC (4:00 PM Indian time - UTC+5:30)
  workflow_dispatch:
# ─────── Job definition ─────────────────────────────────────────
jobs:
  scrape:
    runs-on: ubuntu-latest

    # Path to creds file the script expects
    env:
      GOOGLE_CREDS: ${{ github.workspace }}/credentials.json

    steps:
      # 1️⃣  Pull repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣  Python toolchain (with pip cache)
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # 3️⃣  System packages -- Chromium for Selenium
      - name: Install OS dependencies (headless Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            chromium-browser \
            fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 \
            libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libgtk-3-0 \
            libnspr4 libnss3 libx11-xcb1 libxdamage1 libxrandr2 xdg-utils

      # 4️⃣  Python libs
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install \
            selenium \
            webdriver-manager \
            gspread \
            google-auth \
            tqdm \
            beautifulsoup4

      # 5️⃣  Drop the service-account JSON from a secret
      - name: Write Google service account credentials
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > credentials.json

      # 6️⃣  Launch the scraper
      - name: Run windows 
        run: python gems.py

      # (Optional) 7️⃣  Clean up the creds file so it never lingers
      - name: Remove credentials
        if: always()
        run: rm -f credentials.json
